version: 2

project_name: ingitdb

before:
  hooks:
    - go mod tidy

builds:
  - id: ingitdb-windows
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [ CGO_ENABLED=0 ]
    goos: [ windows ]
    goarch: [ amd64 ]
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: zip
    formats: [ zip ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ ingitdb-windows ]

checksum:
  name_template: checksums.txt

scoops:
  - name: ingitdb
    ids:
      - zip
    description: "A CLI for a schema-validated, AI-native database backed by a Git repository."
    url_template: "https://github.com/ingitdb/ingitdb-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: https://ingitdb.com
    license: MIT
    repository:
      owner: ingitdb
      name: scoop-bucket
      branch: main
      token: "{{ .Env.INGITDB_GORELEASER_GITHUB_TOKEN }}"

release:
  skip_upload: true
