version: 2

project_name: ingitdb

before:
  hooks:
    - go mod tidy

builds:
  - id: ingitdb-linux
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: ingitdb-windows
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [amd64]
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: tarball
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ingitdb-linux]
    files:
      - README.md
      - LICENSE*

  - id: zip
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ingitdb-windows]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: ingitdb
    name: ingitdb-cli

winget:
  - name: ingitdb
    publisher: ingitdb
    publisher_url: https://ingitdb.com
    package_identifier: ingitdb.ingitdb
    license: MIT
    homepage: https://ingitdb.com
    short_description: "A CLI for a schema-validated, AI-native database backed by a Git repository."
    url_template: "https://github.com/ingitdb/ingitdb-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    description: |
      ingitdb is a developer-grade, schema-validated, AI-native database
      whose storage engine is a Git repository. Records are YAML/JSON files,
      collections and schemas are defined declaratively.
    repository:
      owner: ingitdb
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
