version: 2

project_name: ingitdb

chocolateys:
  - name: ingitdb
    ids:
      - zip
    title: ingitdb
    authors: ingitdb
    summary: "A CLI for a schema-validated, AI-native database backed by a Git repository."
    description: |
      ingitdb is a developer-grade, schema-validated, AI-native database
      whose storage engine is a Git repository. Records are YAML/JSON files,
      collections and schemas are defined declaratively.
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"

release:
  skip_upload: true
