version: 2

project_name: ingitdb

winget:
  - name: ingitdb
    publisher: ingitdb
    publisher_url: https://ingitdb.com
    package_identifier: ingitdb.ingitdb
    license: MIT
    homepage: https://ingitdb.com
    short_description: "A CLI for a schema-validated, AI-native database backed by a Git repository."
    description: |
      ingitdb is a developer-grade, schema-validated, AI-native database
      whose storage engine is a Git repository. Records are YAML/JSON files,
      collections and schemas are defined declaratively.
    repository:
      owner: ingitdb
      name: winget-pkgs
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

release:
  github:
    owner: ingitdb
    name: ingitdb-cli
  disable: true

builds:
  - id: ingitdb-windows
    main: ./cmd/ingitdb
    binary: ingitdb
    env: [ CGO_ENABLED=0 ]
    goos: [ windows ]
    goarch: [ amd64 ]
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: zip
    formats: [ zip ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ ingitdb-windows ]

