version: "2"

run:
  timeout: 3m

issues:
  exclude-use-default: false
  exclude: []
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
