# You can link a specific collection or a directory with collections
rootCollections:
  companies: test-ingitdb/companies
  # Namespace import: imports all root collections from another .ingitdb.yaml
  # with the key prefix (e.g., todo.* imports todo.statuses, todo.tags, todo.tasks)
  todo.*: docs/demo-apps/todo
  agile.*: docs/demo-apps/agile-ledger

# `languages` list supported languages should preferably use `ISO 639-1`
#  or alternatively `IERF BCP 47` (`RFC 5646` / `RFC 4647`).
#
# Examples:
#  - required: en
#  - required: es-ES
#  - required: es-MX
#  - optional: ru
#
# The required languages should be before the optional ones.
# Language selector will show languages in order defined in this list.
languages:
  - required: en
  - optional: fr
  - optional: es
  - optional: ru
