# You can link a specific collection or a directory with collections
rootCollections:
  companies: test-ingitdb/companies
  todo.statuses: test-ingitdb/todo/statuses
  todo.tags: test-ingitdb/todo/tags
  todo.tasks: test-ingitdb/todo/tasks
  # Namespace import: imports all root collections from another .ingitdb.yaml
  # with "agile." prefix (e.g., agile.teams)
  agile.*: docs/demo-apps/agile-ledger

# `languages` list supported languages should preferably use `ISO 639-1`
#  or alternatively `IERF BCP 47` (`RFC 5646` / `RFC 4647`).
#
# Examples:
#  - required: en
#  - required: es-ES
#  - required: es-MX
#  - optional: ru
#
# The required languages should be before the optional ones.
# Language selector will show languages in order defined in this list.
languages:
  - required: en
  - optional: fr
  - optional: es
  - optional: ru
